### PR TITLE
Use SRV lookups for DNS resolving

### LINKED ISSUE #1: Switch to SRV lookups for service endpoints
Currently connections will be made to the service IP rather than the pod IPs. Switching to SRV records will enable discovery of pod IPs & ports from DNS.

I'll submit a PR to see how this looks & what you think.

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #1.

### CODE REVIEW

**Comment by purplefox** [comment]
When using the plugin with this PR I get the following error when hazelcast nodes try and connect with each other:

INFO: [172.17.0.4]:5701 [dev] [3.6-EA2] Connection [Address[172.30.242.17]:80] lost. Reason: java.io.EOFException[Could not read protocol type!]

What's interesting is 172.30.242.17 is not the IP of a pod.

Pod ips are:

172.17.0.7
172.17.04

So it's trying to connect to the wrong nodes who answer with something unexpected.

This would imply the SRV records don't contain the IP  addresses of the pods.

**Comment by noctarius** [comment]
@jimmidyson any idea? haven't tested yet.

**Comment by purplefox** [comment]
BTW my quickstart that demonstrates the issue can be seen here:

https://github.com/purplefox/ipaas-quickstarts/tree/master/quickstart/vertx/eventbus

**Comment by purplefox** [comment]
Even before the SRV change I'm not really sure how it would work - with an A record, the IP address of the service would be returned.

This would then proxy through to one of the nodes in the cluster. The assumption being I guess that the node would then tell the connecting node about the other nodes in the cluster. However, couldn't the service just connect the node back to itself, as the loadbalancing is random, in which case it would never know about the other nodes.

Perhaps I am missing something but not really sure how this is supposed to work.

**Comment by jimmidyson** [comment]
Well it looked like it was working properly but I just realised I'd used a headless service for the discovery. That creates SRV records for each pod/port combination targeted in the selector so works properly.

**Comment by purplefox** [comment]
I see, lemme try configuring it as a headless service :)

**Comment by purplefox** [comment]
Ah, but won't a headless service mean no load balancing? We want load-balancing in this case as it's a webapp

**Comment by noctarius** [comment]
Yeah the dns was broken before, i wrote this when I planned to tunnel hazelcast through https

**Comment by jimmidyson** [comment]
Do you use the same service for web traffic & cluster comms? They should be separate services shouldn't they?

This is my preferred way to do clustering discovery in Kubernetes. The service doesn't need an allocated IP (i.e. it's headless) as no traffic will go to the cluster comms port.

As an example with Elasticsearch I use 2 services, one for REST API (called `elasticsearch`) that clients connect to & one headless service for cluster discovery (called `elasticsearch-masters`) that cluster members use for discovery. No cluster traffic goes through the service IP.

DNS queries for cluster comms:

```
$ dig elasticsearch-masters.demo.svc.cluster.local SRV +short
10 100 9300 8f89f1b7._unknown-port-9300._tcp.elasticsearch-masters.demo.svc.cluster.local

$ dig 8f89f1b7._unknown-port-9300._tcp.elasticsearch-masters.demo.svc.cluster.local A +short
172.17.0.6
```

**Comment by noctarius** [comment]
You don't want load balancing for Hazelcast (client -> server, server -> server)

**Comment by purplefox** [comment]
I don't want a service for the cluster communication. I only need a service for the web traffic.

The hazelcast nodes need a mechanism to discover each other. Basically I just want some way for the nodes to be able to see the pod ip addresses of the other nodes.

**Comment by jimmidyson** [comment]
Right & the way to do that is by a headless service & use DNS or by querying the API server. Querying the API server requires karma for the service account the pod runs under.

**Comment by purplefox** [comment]
But if I use a headless service won't I lose load balancing for web traffic?

**Comment by jimmidyson** [comment]
With the Elasticsearch example I used above, there are 2 services involved, one headless for cluster discovery, one normal service for client's connecting to REST API.

**Comment by noctarius** [comment]
you configure multiple services, only the hazelcast one is headless

**Comment by purplefox** [comment]
I am pretty much a k8s newb - is it possible to have multiple services pointing at the same set of pods? Any particular pod is both a web server and a hazelcast node.

**Comment by noctarius** [comment]
me too, sorry :)

**Comment by jimmidyson** [comment]
Absolutely possible. Service endpoints are selected by the label selector of the service. These can overlap, be subset/superset of other service endpoints, etc - do anything you like really.

(Don't get this confused with replication controllers which should never overlap selectors.)

**Comment by purplefox** [comment]
Cool!. Do you have an example Maven project I can copy where a pod is configured with two services?

**Comment by purplefox** [comment]
Looking here:

https://github.com/purplefox/ipaas-quickstarts/blob/master/quickstart/vertx/eventbus/pom.xml#L55

I can see how the service name is configured for a quickstart, but not sure how to configure multiple.

**Comment by noctarius** [comment]
Should I revert this commit for now?

**Comment by purplefox** [comment]
Aiui, I think this is good if it's documented it must be used with headless services.

But I don't think this is sufficient. I believe the HZ Kubernetes plugin should allow pods from different services to also form a cluster - so I think you should be able to supply a set of service names, or perhaps better a selector that allowed you to include services based on their names, e.g. all services starting with "foo." (e.g. foo.microservice1, foo.microservice2, etc)

**Comment by jimmidyson** [comment]
@purplefox You would probably be better off doing that with a single service that selects pods based on labels. Each pod would have a common subset of labels you could use for the cluster.

**Comment by purplefox** [comment]
Cool. I didn't know you could do that. So it's possible to create a service that forms a "view" over other services? Perfect.

**Comment by jimmidyson** [comment]
Absolutely.

**Pull request merged**
