### PR TITLE
Upgrade Hazelcast to version 3.7.3

### PR DESCRIPTION
**Pull request by oscerd**
Just a little version upgrade :-)

### CODE REVIEW

**Comment by noctarius** [comment]
Hey @oscerd ,
We're in the process to move the kubernetes plugin to the official Hazelcast repositories. Therefore we need to have the CLA signed before merging further code. Can you please sign it? :)
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

And thanks for your contribution!
Chris

**Comment by oscerd** [comment]
I'll do, sure :-)

**Comment by noctarius** [comment]
CLA not signed but newer version is already available anyways :) Skipped to merge, still thanks for the help.

**Comment by oscerd** [comment]
Sorry about this, There were holidays in the middle and I forget about the CLA. Sorry :-)

**Comment by noctarius** [comment]
no worries, there's always the chance to send another PR :D

**Comment by oscerd** [comment]
:-)

**Pull request closed without merging**
