### PR TITLE
Upgrade kubernetes-client dependency

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by noctarius** [comment]
Why is the client version lower?

**Comment by noctarius** [comment]
Automatic token handling didn't work on openshift for an unknown reason. I have this "workaround" from the cassandra implementation.

**Comment by jimmidyson** [comment]
Actually it's not... old dependency was on fabric8 kubernetes-api which was (is?) a thin wrapper around the client which is no longer needed. Transitively you were dependent on 1.3.53 of the kubernetes-client library.

Automatic token handling should work now - we use it in a number of places.

**Comment by noctarius** [comment]
Can you please split them into different PRs?

**Comment by jimmidyson** [comment]
Sure.

**Comment by jimmidyson** [comment]
Dropped the token handling changes from this PR

**Comment by noctarius** [comment]
Thanks :)

**Pull request merged**
